### ISSUE TITLE
Does this gem still work?

### ISSUE THREAD

**Issue by devmod** [jwaterfaucett/youtrack#6]
Tried to create an issue copying the example provided but it fails as follow:

> `/Users/devmod/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:18:in`block in initialize_http_header': undefined method `strip' for nil:NilClass (NoMethodError)
>     from /Users/devmod/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:16:in`each'
>     from /Users/devmod/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/header.rb:16:in `initialize_http_header'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:178:in`setup_raw_request'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:115:in `perform'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty.rb:560:in`perform_request'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty.rb:512:in `put'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/youtrack-0.0.11/lib/youtrack/resources/base.rb:40:in`put'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/youtrack-0.0.11/lib/youtrack/resources/issue.rb:25:in `create'
>     from export_ch.rb:100:in`block in <main>'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty/response.rb:81:in `each'
>     from /Users/devmod/.rvm/gems/ruby-2.3.0/gems/httparty-0.14.0/lib/httparty/response.rb:81:in`method_missing'
>     from export_ch.rb:96:in `<main>'
> `

Any ideas? Thanks!

**Comment by devmod** [comment]
Ha! Just figured it out- I needed to set the url as https and not http!
